apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: web
  annotations:
	  flux.weave.works/tag.<containername>: glob:hello-world*
	  flux.weave.works/automated: 'true'
spec:
  containers:
    - name: front-end
      image: mukeshpanigrahi/hello-world-repo
      ports:
        - containerPort: 80
