apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: mukeshpanigrahi/hello-world-repo
      ports:
        - containerPort: 80
